// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRVTQOYo2UM6Ck7GiJD0XT1I5gzdG1jqc',
    appId: '1:27296212358:web:9a6f368fb945d7ac42b807',
    messagingSenderId: '27296212358',
    projectId: 'plantcare-bc34a',
    authDomain: 'plantcare-bc34a.firebaseapp.com',
    storageBucket: 'plantcare-bc34a.appspot.com',
    measurementId: 'G-TPSTW7EC06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGk4WkmV5no6w_LuL92S5gA7CVZDU9S9w',
    appId: '1:27296212358:android:0aff832f8cdcb22442b807',
    messagingSenderId: '27296212358',
    projectId: 'plantcare-bc34a',
    storageBucket: 'plantcare-bc34a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgOqMV8fxbpOaEYKcFQ6A0iW29krR6uBU',
    appId: '1:27296212358:ios:b360b8bef08b478342b807',
    messagingSenderId: '27296212358',
    projectId: 'plantcare-bc34a',
    storageBucket: 'plantcare-bc34a.appspot.com',
    iosBundleId: 'com.example.plantcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgOqMV8fxbpOaEYKcFQ6A0iW29krR6uBU',
    appId: '1:27296212358:ios:b360b8bef08b478342b807',
    messagingSenderId: '27296212358',
    projectId: 'plantcare-bc34a',
    storageBucket: 'plantcare-bc34a.appspot.com',
    iosBundleId: 'com.example.plantcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRVTQOYo2UM6Ck7GiJD0XT1I5gzdG1jqc',
    appId: '1:27296212358:web:6f19d0b3936d2e2d42b807',
    messagingSenderId: '27296212358',
    projectId: 'plantcare-bc34a',
    authDomain: 'plantcare-bc34a.firebaseapp.com',
    storageBucket: 'plantcare-bc34a.appspot.com',
    measurementId: 'G-R644MQ43YY',
  );
}
